Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
p_sp_clusters = .9
sp_df2 = mlsim.anomaly.geometric_2d_gmm_sp(r_clusters,cluster_size,cluster_spread,
                                    p_sp_clusters, domain_range,k,N,p_clusters)
sp_plot(sp_df2,'x1','x2','color')
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[3], line 4[0m
[1;32m      1[0m p_sp_clusters [38;5;241m=[39m [38;5;241m.9[39m
[1;32m      2[0m sp_df2 [38;5;241m=[39m mlsim[38;5;241m.[39manomaly[38;5;241m.[39mgeometric_2d_gmm_sp(r_clusters,cluster_size,cluster_spread,
[1;32m      3[0m                                     p_sp_clusters, domain_range,k,N,p_clusters)
[0;32m----> 4[0m [43msp_plot[49m[43m([49m[43msp_df2[49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mx1[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mx2[39;49m[38;5;124;43m'[39;49m[43m,[49m[38;5;124;43m'[39;49m[38;5;124;43mcolor[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/work/ml-sim/ml-sim/mlsim/anomaly/plot_utils.py:27[0m, in [0;36msp_plot[0;34m(df, x_col, y_col, color_col, ci, domain_range, ax, aggplot, x_jitter, height, legend)[0m
[1;32m     23[0m n_markers [38;5;241m=[39m df[color_col][38;5;241m.[39munique()[38;5;241m.[39mshape[[38;5;241m0[39m] [38;5;66;03m# number unique[39;00m
[1;32m     24[0m cur_markers [38;5;241m=[39m all_markers[:n_markers]
[0;32m---> 27[0m [43msns[49m[38;5;241;43m.[39;49m[43mlmplot[49m[43m([49m[43mx_col[49m[43m,[49m[43m [49m[43my_col[49m[43m,[49m[43m [49m[43mdata[49m[38;5;241;43m=[39;49m[43mdf[49m[43m,[49m[43m [49m[43mhue[49m[38;5;241;43m=[39;49m[43mcolor_col[49m[43m,[49m[43m [49m[43mci[49m[38;5;241;43m=[39;49m[43mci[49m[43m,[49m
[1;32m     28[0m [43m               [49m[43mmarkers[49m[43m [49m[38;5;241;43m=[39;49m[43mcur_markers[49m[43m,[49m[43m [49m[43mpalette[49m[38;5;241;43m=[39;49m[38;5;124;43m"[39;49m[38;5;124;43mSet1[39;49m[38;5;124;43m"[39;49m[43m,[49m[43mx_jitter[49m[38;5;241;43m=[39;49m[43mx_jitter[49m[43m,[49m
[1;32m     29[0m [43m               [49m[43mheight[49m[38;5;241;43m=[39;49m[43mheight[49m[43m,[49m[43mlegend[49m[38;5;241;43m=[39;49m[43mlegend[49m[43m)[49m
[1;32m     30[0m [38;5;28;01mif[39;00m aggplot:
[1;32m     31[0m     [38;5;66;03m# adda whole data regression line, but don't cover the scatter data[39;00m
[1;32m     32[0m     sns[38;5;241m.[39mregplot(x_col, y_col, data[38;5;241m=[39mdf, color[38;5;241m=[39m[38;5;124m'[39m[38;5;124mblack[39m[38;5;124m'[39m, scatter[38;5;241m=[39m[38;5;28;01mFalse[39;00m, ci[38;5;241m=[39mci,)

[0;31mTypeError[0m: lmplot() got multiple values for argument 'data'

